version: '3.2'

services:
  # portainer can only view containers running on its own node
  # unless we run an agent on each node, then connect the frontend
  # to the agents
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  frontend:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - '9000:9000'
    networks:
      - agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${SRV_APPDATA}/persistent:/data:rw
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1

networks:
  agent_network:
    driver: overlay
    attachable: true
